name: my_style_closet
description: "A virtual closet application for managing your clothing items and outfits."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^4.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  http: ^1.1.2
  supabase_flutter: ^1.10.25
  uuid: ^3.0.7
  intl: ^0.19.0
  background_remover: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
